In [94]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [95]:
#напишіть функцію гіпотези лінійної регресії у векторному вигляді;
def h(X, w):
    return np.dot(X, w)

In [96]:
# створіть функцію для обчислення функції втрат у векторному вигляді;

def loss_function(X, y, w):
    return np.square(h(X, w) - y).sum() / (2 * len(X))

In [97]:
# реалізуйте один крок градієнтного спуску;
def gradient_step(X, y, w, learning_rate):
    m = len(y)
    grad = (X.T @ (h(X, w) - y)) / m
    w -= learning_rate * grad
    return w

In [98]:
# градієнт спуску

def gradient(X, y, learning_rate, num_iter, eps):
    ones = np.ones((X.shape[0], 1))
    X = np.hstack((ones, X))

    w = np.zeros(X.shape[1])  # Ініціалізація ваг

    loss = loss_function(X, y, w)
    loss_history = [loss]

    for _ in range(num_iter):
        w = gradient_step(X, y, w, learning_rate)

        loss = loss_function(X, y, w)
        if abs(loss - loss_history[-1]) < eps:
            loss_history.append(loss)
            break

        loss_history.append(loss)

    return w, loss_history

In [99]:
# знайдіть найкращі параметри $\vec{w}$ для датасету прогнозуючу ціну на будинок
# залежно від площі, кількості ванних кімнат та кількості спалень;
df = pd.read_csv("Housing.csv")
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [100]:

norm = df.copy()
columns = ['price', 'area', 'bedrooms', 'bathrooms']
for column in columns[1:]:
    norm[column] = (df[column] - df[column].mean()) / df[column].std()

norm.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,1.045766,1.402131,1.420507,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,1.755397,1.402131,5.400847,4,yes,no,no,no,yes,3,no,furnished
2,12250000,2.216196,0.047235,1.420507,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,1.082630,1.402131,1.420507,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,1.045766,1.402131,-0.569663,2,yes,yes,yes,no,yes,2,no,furnished

In [101]:
X = norm[['area', 'bedrooms', 'bathrooms']].values
y = norm['price'].values

In [102]:
# Параметри градієнтного спуску
learning_rate = 0.001
num_iter = 1000
eps = 1e-12

In [103]:
# Градієнтний спуск
w_gradient, loss_history = gradient(X, y, learning_rate, num_iter, eps)
print('Градієнтний спуск - w:', w_gradient)

Градієнтний спуск - w: [3014024.71220283  568181.32428217  312406.34233568  510639.98109586]

In [104]:
# # Аналітичний розв'язок
X.shape[0]
ones = np.ones((X.shape[0], 1))
X = np.hstack((ones, X))
w_analytical = np.linalg.pinv(X.T @ X) @ X.T @ y
print('Аналітичне рішення - Оптимальне w:', w_analytical)

# regressor = LinearRegression().fit(X, y)
# print(f'Модельні ваги: {regressor.intercept_}, {regressor.coef_}')

Аналітичне рішення - Оптимальне w: [4766729.24770642  821968.58935343  300259.16468032  696447.75898579]

In [105]:
print('Градієнтний спуск             - w:', w_gradient[0:4])
print('Аналітичне рішення - Оптимальне w:', w_analytical[0:4])

Градієнтний спуск             - w: [3014024.71220283  568181.32428217  312406.34233568  510639.98109586]
Аналітичне рішення - Оптимальне w: [4766729.24770642  821968.58935343  300259.16468032  696447.75898579]